### ISSUE TITLE
Dropbox loop 

### ISSUE THREAD

**Issue by ghost** [nao-pon/elFinder#1]
Hi there Nao-pon,

first off, thanks for your great work on elfinder!

I am having issues implementing your dropbox volumedriver:
- When opening a dropbox account for the first time, the time it takes to show some actual files is up and around 3-10 minutes. This shouldn't take so long. Debugging proves that the actual first connect (where it gets the account limits etc) is instant. 
- After the time has passed, dropbox appears in elfinder (sometimes it keeps on loading, and nothing happens - the initial ajax request just keeps on running), and only lists 2 out of the 15 folders in my dropbox. When I head into the directory tree, I see that in these two folders, only a few files are being shown. It seems that something is wrong as not all of the files are being loaded.
  Note: I do see a cache file being built (its around 266kb, not sure whether that's very 'big'.

Misc info:
Server is a dedicated server with php 5.3.6, 4GB ram, and 100mBit uplink.

My options in the connector.php file:

``` php
$opts = array(
    // 'debug' => true,
    'roots' => array(
        array(
            'driver' => 'Dropbox',
            'path' => '/',
            'alias' => 'Dropbox',
            'tmbPath' => '.tmb',
            'treeDeep' => 1,
            'consumerKey' => ELFINDER_DROPBOX_CONSUMERKEY,
            'consumerSecret' => ELFINDER_DROPBOX_CONSUMERSECRET,
            'accessToken' => 'xxxxxx',
            'accessTokenSecret' => 'yyyyy',
            'metaCachePath' => '../files/.tmb',
            'utf8fix' => true,
            // 'separator' => ':',
            'attributes' => array(
                array(
                    'pattern' => '~/\.~',
                    // 'pattern' => '/^\/\./',
                    'read' => false,
                    'write' => false,
                    'hidden' => true,
                    'locked' => false
                )
            ),
        )
    )
);
```

**Comment by nao-pon** [comment]
Hi erikhoeksma, so sorry it's too late.

You should set 'dropboxUid' in roots options.

``` php
array(
    'driver'     => 'Dropbox',
    'path'       => '/',
    'consumerKey'       => ELFINDER_DROPBOX_CONSUMERKEY,
    'consumerSecret'    => ELFINDER_DROPBOX_CONSUMERSECRET,
    'accessToken'       => 'xxxxxxxxxxxxxxx',
    'accessTokenSecret' => 'yyyyyyyyyyyyyyy',
    'dropboxUid'        => 'zzzzzzzz',
    'alias'      => 'Dropbox.com',
    'mimeDetect' => 'internal',
    'tmbURL'     => dirname($_SERVER['PHP_SELF']) . '/files/.tmb',
    'tmbPath'    => dirname(dirname(__FILE__)) . '/files/.tmb',
    'utf8fix'    => true,
    'tmbCrop'    => false,
    'separator' => '/',
    'defaults' => array('read' => true, 'write' => true)
),
```

But if you use Dropbox in roots options so it will permit all people full access. 
Therefore, Dropbox volume uses network volume mounting, and a user usually uses it, mounting it himself.
