### ISSUE TITLE
Search box doesn't work for cp1251

### ISSUE THREAD

**Issue by Winand** [nao-pon/elFinder#15]
As you know, i've set `encoding=cp1251`.) But search box doesn't find files with cyrillic symbols, there's no such an issue with latin filenames.
I use elfinder-2.x-88c7e9d.

**Comment by Winand** [comment]
It works, but is case-sensitive with cp1251 !

**Comment by nao-pon** [comment]
What about next solution?

php/elFinderVolumeDriver.class.php L.4104-

``` php
    protected function stripos($haystack , $needle , $offset = 0) {
        if (function_exists('mb_stripos')) {
            return mb_stripos($haystack , $needle , $offset);
        } else if (function_exists('mb_strtolower') && function_exists('mb_strpos')) {
            return mb_strpos(mb_strtolower($haystack), mb_strtolower($needle), $offset);
        } 
        return stripos($haystack , $needle , $offset);
    }
```

to

``` php
    protected function stripos($haystack , $needle , $offset = 0) {
        $encoding = $this->encoding? $this->encoding : 'UTF-8';
        if (function_exists('mb_stripos')) {
            return mb_stripos($haystack , $needle , $offset, $encoding);
        } else if (function_exists('mb_strtolower') && function_exists('mb_strpos')) {
            return mb_strpos(mb_strtolower($haystack, $encoding), mb_strtolower($needle, $encoding), $offset);
        } 
        return stripos($haystack , $needle , $offset);
    }
```

**Comment by nao-pon** [comment]
I made mistake. next is correct

``` php
    protected function stripos($haystack , $needle , $offset = 0) {
        if (function_exists('mb_stripos')) {
            return mb_stripos($haystack , $needle , $offset, 'UTF-8');
        } else if (function_exists('mb_strtolower') && function_exists('mb_strpos')) {
            return mb_strpos(mb_strtolower($haystack, 'UTF-8'), mb_strtolower($needle, 'UTF-8'), $offset);
        } 
        return stripos($haystack , $needle , $offset);
    }
```

**Comment by Winand** [comment]
It's ok.
![image](https://cloud.githubusercontent.com/assets/53390/11972187/a746c5bc-a959-11e5-8949-36778ba88df0.png)
p.s. Is white shadow is intended to be in search results? ie9

**Comment by nao-pon** [comment]
> p.s. Is white shadow is intended to be in search results? ie9

Is it also in my demo site?
- Demo site: http://hypweb.net/elFinder-nightly/demo/2.1/

**Comment by Winand** [comment]
~~No, it is not. I've uploaded a file with lower case cyrillic filename, tried to search part of this name in upper case and FAILED.~~ oh, i thought you asked about codepage.) though this looks like a problem too

No, there's no shadow on you site
Here's my shadow (same with IE9 and Vivaldi):
![image](https://cloud.githubusercontent.com/assets/53390/11976340/6c993e98-a988-11e5-87ce-c763b7995fe4.png)
