### ISSUE TITLE
Pixlr error on exit

### ISSUE THREAD

**Issue by dleffler** [nao-pon/elFinder#16]
When using the Pixlr editor it doesn't return correctly. While the actions taken in Pixlr seem to work (save save-copy), it either displays the text from a json upload error on a simple exit from Pixlr without save.

This occurs on your demo http://hypweb.net/elFinder-nightly/demo/2.1_n/#elf_l2_Lw

**Comment by dleffler** [comment]
```
{"error":["errUploadNoFiles"],"debug":{"connector":"php","phpver":"5.5.30","time":0.022396087646484,"memory":"1890Kb \/ 651Kb \/ 256M","upload":"","volumes":[{"id":"l1_","name":"localfilesystem","mimeDetect":"finfo","imgLib":"imagick"},{"id":"l2_","name":"localfilesystem","mimeDetect":"finfo","imgLib":"imagick"}],"mountErrors":[]}}
```

**Comment by nao-pon** [comment]
@dleffler Thanks! :+1:
