### ISSUE TITLE
Netunmount

### ISSUE THREAD

**Issue by SJamuna** [nao-pon/elFinder#2]
Hi,
Netunmount command it is not working.when click on the folder that time that netunmount icon is in disable condition.how can i enable the icon when clicking on the folder.i attached screenshot like this oly it is showing.
![Screenshot](https://f.cloud.github.com/assets/2928607/32805/6496b3aa-5045-11e2-91a2-803bf49d1f80.png)

**Comment by nao-pon** [comment]
Net Mount & Net Un-Mount use FTP or DropBox volume driver. Please check your connector(.minimal).php.

If you want use FTP driver. Please remove comment out ("//").

ex.
`// include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeFTP.class.php';`
to
`include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeFTP.class.php';`

so you can use "Mount network volume" and "Unmount" with right click on Netmount drive icon in dirctory window.

![unmount](http://i.imm.io/QLbS.jpeg)

**Comment by SJamuna** [comment]
i uncommented that one but it is showing same thing..
![Screenshot-3](https://f.cloud.github.com/assets/2928607/34009/2aaff1bc-50ed-11e2-8ebf-c796e7414795.png)
i need unmount option with right click.

**Comment by nao-pon** [comment]
Please right click on your "Mounted Volumes" for un-mount. :-)

**Comment by SJamuna** [comment]
i checked but it showing like this screenshot
![Screenshot from 2012-12-31 12:07:47](https://f.cloud.github.com/assets/2928607/36343/2559d29e-5315-11e2-8f06-513a0bcaef7a.png)

i wrote the code like this pls check once if it is any mistake is there are not

elFinder.class.php:-
 protected function netmount($args) {
                $options  = array();
                $protocol = $args['protocol'];

```
            if ($protocol === 'netunmount') {
                    if (isset($_SESSION) && is_array($_SESSION) && isset($_SESSION['netVolumes'][$args['host']]))                   {
                            unset($_SESSION['netVolumes'][$args['host']]);
                            return array('sync' => true);
                    } else {
                            return array('error' => $this->error(self::ERROR_NETUNMOUNT));
                    }
            }
                    $options['netkey'] = $key;
   }
```

elFinderVolumeDriver.php:-

---

if (isset($this->options['netkey']) && $path === $this->root) {
                        $stat['netkey'] = $this->options['netkey'];
                }

elFinder.min.css:-

---

```
 .elfinder-button-icon-netunmount{background-position:0 -96px}
```

elFinder.min.js:-

---

commands:   ["open","reload","home","up","back","forward","getfile","quicklook","download","rm","duplicate","rename","mkdir","mkfile","upload","copy","cut","paste","edit","extract","archive","search","info","view","help","resize","sort","netunmount"],

contextmenu:{navbar:["open","|","copy","cut","paste","duplicate","|","rm","|","info","|","netunmount"],

elFinder.prototype.commands.netunmount=function(){
    varb=this;this.alwaysEnabled=!0,
    this.updateOnSelect=!1,
    this.drivers=[

```
],
this.handlers={
    load: function(){
        b.drivers=this.fm.netDrivers
    }
},
this.getstate=function(a){
    varb=this.fm;return!!a&&this.drivers.length&&!this._disabled&&b.file(a[
        0
    ]).netkey?0: -1
},
this.exec=function(b){
    varc=this,
    d=this.fm,
    e=a.Deferred().fail(function(a){
        a&&d.error(a)
    }),
    f=d.file(b[
        0
    ]);if(this._disabled){
        returne.reject()
    }if(!e.isRejected()){
        d.confirm({
            title: c.title,
            text: d.i18n("confirmUnmount",
            f.name),
            accept: {
                label: "btnUnmount",
                callback: function(){
                    d.request({
                        data: {
                            cmd: "netmount",
                            protocol: "netunmount",
                            host: f.netkey,
                            user: "dum",
                            pass: "dum"
                        },
                        notify: {
                            type: "netunmount",
                            cnt: 1
                        },
                        preventFail: !0
                    }).fail(function(a){
                        e.reject(a)
                    }).done(function(a){
                        e.promise()
                    })
                }
            },
            cancel: {
                label: "btnCancel",
                callback: function(){
                    e.reject()
                }
            }
        })
    }return e
}
```

},

elFinder.LANG.js:-

---

   ****\* errors *****
  'errNetUnMount'        : 'Unable to unmount', 

   ****\* commands names *****
  'cmdnetunmount': 'Unmount', 

   ****\* buttons ******
    'btnApprove': 'Goto $1 & approve',
    'btnUnmount': 'Unmount',

   ****\* notifications ******
   'ntfnetunmount': 'Unmounting network volume',

   ****\* messages ******
   'confirmUnmount'      : 'Are you unmount $1?',

**Comment by nao-pon** [comment]
The "netunmount" cmd enabled only netmount volume. Please check next video.

http://youtu.be/BQ-IYzTez8A

**Comment by SJamuna** [comment]
but in my project mount volume is in one file.If i click on mount volume button means that mounted files are showing in another file.
for eg :
before mount volumes
![Screenshot from 2012-12-31 16:06:56](https://f.cloud.github.com/assets/2928607/36453/7660f55c-5336-11e2-9695-c93b9abc1566.png)
after mount volumes
![Screenshot from 2012-12-31 16:07:31](https://f.cloud.github.com/assets/2928607/36454/956f9d54-5336-11e2-9ac8-fb30d0da4bb1.png)
now how can i unmount this WIN-8S2GMA6R65C mounted volume.

**Comment by nao-pon** [comment]
Are you using nao-pon/elFinder:2.x_n?
"unnetmount" command of 2.x_n is a command which unmounts the volume mounted by "Mount network volume" of elFinder. 
Therefore, the volume mounted on the local server cannot be unmounted.
