### ISSUE TITLE
Archive Functionality is not working

### ISSUE THREAD

**Issue by SJamuna** [nao-pon/elFinder#3]
While creating archive i m getting unable to create archive error in server.
![Screenshot from 2013-01-05 19:12:17](https://f.cloud.github.com/assets/2928607/45063/c0850906-573d-11e2-8ffe-55ce9e3c4ab2.png)

**Comment by nao-pon** [comment]
What is the volume driver using?

**Comment by SJamuna** [comment]
Thanks i understood the problem because of that files are read oly files.So i ll remove that option in mounted volumes but i need that option in test volume.In elfinder.org they having demo and test here VMs.Test here options are not visibiling in demo.same like i have to create how can i create right options only in test volumes.
in test here:
![Screenshot from 2013-01-07 12:11:23](https://f.cloud.github.com/assets/2928607/46782/5c664648-5895-11e2-9833-eac7ce4aa862.png)
in demo:
![Screenshot from 2013-01-07 12:11:05](https://f.cloud.github.com/assets/2928607/46781/4fcf448e-5895-11e2-8c22-383a654b8020.png)
